services:
  app:
    image: traefik:v3.1
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare_api_key
      - TZ=America/Sao_Paulo
    networks:
      - proxy-network
    healthcheck:
      test:
        - CMD
        - traefik
        - healthcheck
        - '--ping'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command:
      - '--global.checkNewVersion=false'
      - '--global.sendAnonymousUsage=false'
      - '--api=true'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--ping=true'
      - '--ping.entryPoint=traefik'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.websecure.http.tls=true'
      - '--entrypoints.websecure.http.tls.certResolver=cloudflare'
      - '--entrypoints.websecure.http3.advertisedPort=443'
      - '--entrypoints.traefik.address=:8080'
      - '--providers.swarm=true'
      - '--providers.swarm.exposedByDefault=false'
      - '--providers.swarm.network=traefik_proxy-network'
      - '--providers.swarm.watch=true'
      - '--providers.swarm.endpoint=unix:///var/run/docker.sock'
      - '--providers.swarm.refreshSeconds=15'
      - '--providers.file.filename=/etc/traefik/dynamic.yml'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.cloudflare.acme.email=henrique@henriqzimer.com.br'
      - '--certificatesresolvers.cloudflare.acme.storage=/tmp/acme.json'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge=true'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=60s'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.disablepropagationcheck=true'
      - '--log.level=INFO'
      - '--log.format=json'
      - '--accesslog=true'
      - '--accesslog.format=json'
      - '--accesslog.bufferingsize=100'
      - '--metrics.prometheus=true'
      - '--metrics.prometheus.addEntryPointsLabels=true'
      - '--metrics.prometheus.addServicesLabels=true'
      - '--metrics.prometheus.addRoutersLabels=true'
    configs:
      - source: dynamic_config
        target: /etc/traefik/dynamic.yml
        mode: 444
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 30s
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 128M
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.henriqzimer.com.br`)
        - traefik.http.routers.traefik-dashboard.entrypoints=websecure
        - traefik.http.routers.traefik-dashboard.tls=true
        - traefik.http.routers.traefik-dashboard.tls.certresolver=cloudflare
        - traefik.http.routers.traefik-dashboard.service=api@internal
        - traefik.http.routers.traefik-dashboard.middlewares=admin-auth@file
        - traefik.http.services.traefik.loadbalancer.server.port=8080
    secrets:
      - cloudflare_api_key
      - traefik_dashboard_auth

networks:
  proxy-network:
    driver: overlay
    driver_opts:
      encrypted: 'true'
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16

configs:
  dynamic_config:
    file: ./dynamic.yml

secrets:
  cloudflare_api_key:
    file: ./cloudflare_api_key.txt
  traefik_dashboard_auth:
    file: ./traefik_dashboard_auth.txt
