# Traefik Static Configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Log configuration
log:
  level: INFO
  filePath: /var/log/traefik/traefik.log
  format: json

# Access log
accessLog:
  filePath: /var/log/traefik/access.log
  format: json
  bufferingSize: 100

# API and Dashboard
api:
  dashboard: true
  debug: false
  insecure: false

# Ping endpoint for health checks
ping:
  entryPoint: web

# Entry Points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        options: default
    http3:
      advertisedPort: 443

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    swarmMode: true
    swarmModeRefreshSeconds: "15s"
    network: proxy-network
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# Certificate Resolvers
certificatesResolvers:
  cloudflare:
    acme:
      email: henrique@henriqzimer.com.br
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 30s
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
      keyType: EC256

# Metrics
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# Tracing (opcional)
tracing:
  jaeger:
    samplingType: const
    samplingParam: 1.0
    localAgentHostPort: 127.0.0.1:6831