---
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      TZ: America/Sao_Paulo
    secrets:
      - db_password
    networks:
      - website-network
    healthcheck:
      test:
        - CMD-SHELL
        - 'mysqladmin ping -h localhost -u root --password="$$(cat /run/secrets/db_password)" --silent || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 30s
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  app:
    image: wordpress:latest
    volumes:
      - app_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DEBUG=0
      - WORDPRESS_CONFIG_EXTRA=
        define('WP_MEMORY_LIMIT', '256M');
        define('AUTOMATIC_UPDATER_DISABLED', true);
        define('WP_AUTO_UPDATE_CORE', false);
        define('DISALLOW_FILE_EDIT', true);
        define('FORCE_SSL_ADMIN', true);
      - TZ=America/Sao_Paulo
    secrets:
      - db_password
    networks:
      - website-network
      - proxy-network
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:80/wp-admin/install.php || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 30s
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 256M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD_FILE=/run/secrets/db_password
      - UPLOAD_LIMIT=256M
      - MEMORY_LIMIT=256M
      - MAX_EXECUTION_TIME=300
      - TZ=America/Sao_Paulo
      - PMA_ABSOLUTE_URI_FILE=/run/secrets/phpmyadmin_url
    secrets:
      - db_password
      - phpmyadmin_url
    networks:
      - website-network
      - proxy-network
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:80/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 30s
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 128M

volumes:
  db_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=altaria.henriqzimer.com.br,nfsvers=4,rw
      device: ":/mnt/altaria/docker/wordpress/db"
  app_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=altaria.henriqzimer.com.br,nfsvers=4,rw
      device: ":/mnt/altaria/docker/wordpress/app"

networks:
  website-network:
    driver: overlay
    driver_opts:
      encrypted: "true"
    attachable: true
  proxy-network:
    external: true
    name: cloudflared_proxy-network

secrets:
  db_password:
    file: ./wordpress_db_password.txt
  phpmyadmin_url:
    file: ./phpmyadmin_url.txt
