services:
  tunnel-swarm:
    image: cloudflare/cloudflared:latest
    environment:
      TUNNEL_TOKEN_FILE: /run/secrets/tunnel_swarm_token
    networks:
      - proxy-network
    healthcheck:
      test:
        - CMD
        - cloudflared
        - '--help'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    command: tunnel run
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    secrets:
      - tunnel_swarm_token

  tunnel-services:
    image: cloudflare/cloudflared:latest
    environment:
      TUNNEL_TOKEN_FILE: /run/secrets/tunnel_service_token
    networks:
      - proxy-network
    healthcheck:
      test:
        - CMD
        - cloudflared
        - '--help'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    command: tunnel run
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    secrets:
      - tunnel_service_token

networks:
  proxy-network:
    driver: overlay
    driver_opts:
      encrypted: 'true'
    attachable: true

secrets:
  tunnel_swarm_token:
    file: ./cloudflared_tunnel_swarm_token.txt
  tunnel_service_token:
    file: ./cloudflared_tunnel_service_token.txt
