services:
  app:
    image: hashicorp/vault:latest
    volumes:
      - vault_data:/vault/data
    environment:
      VAULT_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://127.0.0.1:8200
      TZ: America/Sao_Paulo
    networks:
      - traefik-proxy
      - cloudflared-proxy
    configs:
      - source: file_config
        target: /vault/config/vault.hcl
        mode: 444
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.http.routers.vault.rule=Host(`vault.henriqzimer.com.br`)
        - traefik.http.routers.vault.entrypoints=websecure
        - traefik.http.routers.vault.tls=true
        - traefik.http.routers.vault.tls.certresolver=cloudflare
        - traefik.http.routers.vault.middlewares=web-chain@file
        - traefik.http.services.vault.loadbalancer.server.port=8200
    entrypoint: vault server -config=/vault/config/vault.hcl

volumes:
  vault_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=altaria.henriqzimer.com.br,nfsvers=4,rw
      device: ":/mnt/altaria/docker/vault/data"

networks:
  traefik-proxy:
    external: true
    name: traefik_proxy-network
  cloudflared-proxy:
    external: true
    name: cloudflared_proxy-network

configs:
  file_config:
    file: ./vault.hcl
